### ISSUE TITLE
cannot connect to 127.0.0.1:58526: 由于目标计算机积极拒绝，无法连接。 (10061)

### ISSUE THREAD

**Issue by viewhang** [makazeu/WsaToolbox_Legacy#15]
![image](https://user-images.githubusercontent.com/26957298/138404677-d316abe7-0a87-4dc0-8d91-952c57a43238.png)

**Comment by viewhang** [comment]
尝试
1.关闭安卓子系统，并点击文件重启，依然连接不上
2.关闭开发者模式，重新打开还是连接不上
3.重启电脑也连接不上

**Comment by 94Bo** [comment]
`netsh winsock reset`

**Comment by viewhang** [comment]
> `netsh winsock reset`

前几天重置网络之后可以了
