### ISSUE TITLE
希望能在文件传输时显示传输标识

### ISSUE THREAD

**Issue by lyb627084437** [makazeu/WsaToolbox_Legacy#18]
经常有传输文件的需求(并且体积一般也不小)，但用它传输文件时既没有传输进度也没有正在传输的标识，我没办法判定文件传完了没有
希望能增加一个标识，至少能够判断当前有没有在传输吧

**Comment by makazeu** [comment]
同意，本来也打算做的，为了赶WSA发布日期，所以这里先简略做了，这几天会做出来。
目前可以通过按钮是否是灰色的来判断。

**Comment by lyb627084437** [comment]
> 同意，本来也打算做的，为了赶WSA发布日期，所以这里先简略做了，这几天会做出来。 目前可以通过按钮是否是灰色的来判断。

明白了，感谢
