### ISSUE TITLE
催更喽

### ISSUE THREAD

**Issue by rnight** [makazeu/WsaToolbox_Legacy#2]
![](https://img.ithome.com/newsuploadfiles/2021/10/f51203e7-e61f-4f86-895e-cda6f52fa169.png)

> 大佬，可以发版了，哈哈哈哈。 @makazeu

**Comment by makazeu** [comment]
我朋友已经在他的B站动态里分享，请参看我的转发。对于英文社区，该Github上的release等到11月后我再同步上传。
Microsoft wants Windows Insiders to focus on testing apps from Amazon appstore at the moment, so I won't upload releases here for now.
