### ISSUE TITLE
如果可以的话，UI能不能往Fluent靠一下

### ISSUE THREAD

**Issue by Aloento** [makazeu/WsaToolbox_Legacy#24]
如题，个人觉得是举手之劳的事情，希望能考虑一下

**Comment by Shomnipotence** [comment]
不是，这是一个exe，所以是一个 Win32 应用程序。其使用了UWP控件，有两种可能，一是通过 XAML island 嵌入，二是通过 WinUI3。如果通过XAML island嵌入，则可以很顺利地升级到 WinUI2.6+，这确实是“举手之劳”，如果使用的是 WinUI3，则目前的 WinUI3 尚不支持 Windows 11 Style。

**Comment by ghost** [comment]
不是啊，winui3已经支持了win11-style-ui了，只是要使用测试版的Windows App SDK，就能在win32里面用fluent的ui库了

**Comment by Shomnipotence** [comment]
> 不是啊winui3已经是win11-style的ui，只是要使用的Windows App SDK支持了，现在在win32里面用的流畅的ui库

Preview1版本不是撤回了么，又发了吗？

**Comment by ghost** [comment]
啊这……刚刚才去微软的doc里看到了提示。。那就等preview3出来吧 ~~或者如果作者自信的话来个实验版app sdk玩玩~~

**Comment by Shomnipotence** [comment]
所以这是一个xaml island还是一个winui3

**Comment by ghost** [comment]
不知道——  
但是如果作者能把后端代码放出来咱就能自己写一个了（

**Comment by Aloento** [comment]
其实是不是Win11的风格都不重要，重要的是
https://developer.microsoft.com/en-us/fluentui

**Comment by Shomnipotence** [comment]
> 不知道—— 但是如果作者能把代码放出来咱自己写一个
在吗

**Comment by Shomnipotence** [comment]
> 不知道—— 但是如果作者能把代码放出来咱自己写一个了（

在吗
