### ISSUE TITLE
修复wsa安装gapps后的连接错误，需要修改连接逻辑，因为gapps会修改设备型号

### ISSUE THREAD

**Issue by cxzlw** [makazeu/WsaToolbox_Legacy#41]
rt
隔壁的apk installer已经支持连接指定设备而不是设备型号是wsa的设备了

**Comment by makazeu** [comment]
请试试 v1.2.8版本  https://github.com/makazeu/WsaToolbox/releases/download/v1.2.8/WsaToolbox_v1.2.8.zip

**Comment by cxzlw** [comment]
thx
