### ISSUE TITLE
无法访问Android/data文件夹

### ISSUE THREAD

**Issue by Super12138** [makazeu/WsaToolbox_Legacy#48]

**Comment by machine-doll** [comment]
正常情况下adb是没有权限访问/data的。在安装了magisk后，给adb提权，就可以访问了

**Comment by Harrilee** [comment]
为什么我这里给ABD授权了，但是还在WSA toolbox里面仍然无法访问`/data`的数据呢？
![image](https://user-images.githubusercontent.com/62582000/143730178-db48c26e-9e8b-425d-ae96-ddfdc351904e.png)
